spring.datasource.url=jdbc:h2:mem:omni;MODE=MySQL;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.jpa.open-in-view=false
